# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClearType',
            fields=[
                ('clear_type', models.IntegerField(primary_key=True, serialize=False)),
                ('clear_type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInfomation',
            fields=[
                ('iidx_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('dj_name', models.CharField(max_length=6)),
                ('single_class', models.CharField(max_length=4)),
                ('double_class', models.CharField(max_length=4)),
                ('prefectures', models.CharField(max_length=20)),
                ('own_arcade', models.CharField(max_length=100)),
                ('single_djpoint', models.FloatField(default=0.0)),
                ('double_djpoint', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('song_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('player_id', models.IntegerField(default=0)),
                ('difficulty', models.CharField(max_length=50)),
                ('ex_score', models.IntegerField(default=0)),
                ('p_great', models.IntegerField(default=0)),
                ('great', models.IntegerField(default=0)),
                ('miss_count', models.IntegerField(default=0)),
                ('clear_type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('song_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('total_notes', models.IntegerField(default=0)),
                ('scrach_notes', models.IntegerField(default=0)),
                ('cn_notes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubTitles',
            fields=[
                ('title_number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('title_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='songs',
            name='subtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeatMania.SubTitles'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('song_name', 'player_id', 'difficulty')]),
        ),
        migrations.AlterUniqueTogether(
            name='songs',
            unique_together=set([('song_name', 'artist_name', 'genre', 'difficulty')]),
        ),
    ]
